networks:
  soatdbproducts:

services:
  db:
    image: mysql
    tty: true
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: soat
      MYSQL_PASSWORD: soat
      MYSQL_DATABASE: soat_products
    networks:
      - soatdbproducts
    ports:
      - "3307:3307"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--user=root",
          "--password=root",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 20s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=soat
      - MYSQL_PASSWORD=soat
      - MYSQL_DATABASE=soat_products
    networks:
      - soatdbproducts
    tty: true
    depends_on:
      db:
        condition: service_healthy
